CREATE DATABASE recicladora;

CREATE TABLE Compra(

IdCompra INTEGER NOT NULL,
Fecha DATE NOT NULL DEFAULT NOW(),
IdProveedor INTEGER NOT NULL,
Cantidad INTEGER NOT NULL,
Total INTEGER NOT NULL,
CONSTRAINT Compra_PKEY PRIMARY KEY (IdCompra)
);


CREATE TABLE Proveedor(

IdProveedor INTEGER NOT NULL,
Nombre  CHARACTER VARYING (20) NOT NULL,
Telefono INTEGER NOT NULL,
Direccion CHARACTER VARYING (20) NOT NULL,
Email CHARACTER VARYING (20) NOT NULL,
CONSTRAINT Proveedor_PKEY PRIMARY KEY (IdProveedor)
);

CREATE TABLE Venta(

IdVenta INTEGER NOT NULL,
Fecha DATE NOT NULL DEFAULT NOW(),
Descripcion  CHARACTER VARYING (500) NOT NULL,
PrecioUnidad INTEGER NOT NULL,
Cantidad INTEGER NOT NULL,
Total INTEGER NOT NULL,
CONSTRAINT Venta_PKEY PRIMARY KEY (IdVenta)
);

CREATE TABLE Reportes(
IdReporte INTEGER NOT NULL,
IdVenta INTEGER NOT NULL,
IdCompra INTEGER NOT NULL,
CONSTRAINT Reporte_PKEY PRIMARY KEY (IdReporte)
);


CREATE TABLE Inventario(
IdProducto INTEGER NOT NULL,
CantidadAlmacenada INTEGER NOT NULL,
IdMateriaPrima INTEGER NOT NULL,
CantidadAlmacenadaP INTEGER NOT NULL,
IdReporte INTEGER NOT NULL
);



CREATE TABLE MateriaPrima(
IdMateriaPrima INTEGER NOT NULL,
Nombre  CHARACTER VARYING (20) NOT NULL,
Descripcion  CHARACTER VARYING (200) NOT NULL,
CONSTRAINT MateriaPrima_PKEY PRIMARY KEY (IdMateriaPrima)
);

CREATE TABLE Producto(
IdProducto INTEGER NOT NULL,
Nombre  CHARACTER VARYING (20) NOT NULL,
Descripcion  CHARACTER VARYING (200) NOT NULL,
CONSTRAINT Producto_PKEY PRIMARY KEY (IdProducto)
);

CREATE TABLE Registros(
IdProveedor INTEGER NOT NULL,
IdCliente INTEGER NOT NULL
);


CREATE TABLE Cliente(

IdCliente INTEGER NOT NULL,
Nombre  CHARACTER VARYING (20) NOT NULL,
Telefono INTEGER NOT NULL,
Direccion CHARACTER VARYING (20) NOT NULL,
Email CHARACTER VARYING (20) NOT NULL,
CONSTRAINT Cliente_PKEY PRIMARY KEY (IdCliente)
);



